CREATE SCHEMA "admin";

CREATE TABLE "cards" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar(150) NOT NULL,
  "date" date NOT NULL,
  "shortDescription" text NOT NULL,
  "description" text,
  "source" text,
  "difficulty" integer NOT NULL,
  "verified" boolean NOT NULL DEFAULT false,
  "categories_id" integer NOT NULL
);

CREATE TABLE "categories" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(100) UNIQUE NOT NULL
);

CREATE TABLE "tags" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(100) UNIQUE NOT NULL
);

CREATE TABLE "categories_tags" (
  "categories_id" integer NOT NULL,
  "tags_id" integer NOT NULL,
  PRIMARY KEY ("categories_id", "tags_id")
);

CREATE TABLE "cards_tags" (
  "cards_id" integer NOT NULL,
  "tags_id" integer NOT NULL,
  PRIMARY KEY ("cards_id", "tags_id")
);

CREATE TABLE "admin"."users" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "email" varchar(255) UNIQUE NOT NULL,
  "name" varchar(255) NOT NULL,
  "password_hash" text NOT NULL
);

ALTER TABLE "cards" ADD FOREIGN KEY ("categories_id") REFERENCES "categories" ("id");

ALTER TABLE "categories_tags" ADD FOREIGN KEY ("categories_id") REFERENCES "categories" ("id") ON DELETE CASCADE ON UPDATE NO ACTION;

ALTER TABLE "categories_tags" ADD FOREIGN KEY ("tags_id") REFERENCES "tags" ("id") ON DELETE CASCADE ON UPDATE NO ACTION;

ALTER TABLE "cards_tags" ADD FOREIGN KEY ("tags_id") REFERENCES "tags" ("id") ON DELETE CASCADE ON UPDATE NO ACTION;

ALTER TABLE "cards_tags" ADD FOREIGN KEY ("cards_id") REFERENCES "cards" ("id") ON DELETE CASCADE ON UPDATE NO ACTION;
